name: Automation tests on GUI app

on:
  workflow_dispatch:
  push:
    branches:
      -main

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 60
        with:
          command: npx cypress run

          browser: chrome
          headed: false
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
